sudo: false
language: python

python:
  - "3.6"

install:
    - pip install pymatgen
    - pip install nose
    - pip install --quiet -r requirements.txt   
script:
    - nosetests -s

      #notifications:
      #  email:
      #    recipients:
      #      - qiang.zhu@unlv.edu
      #    on_success: change
      #    on_failure: always 
