#!/usr/bin/env  python
# encoding: utf-8
from optparse import OptionParser
from pyxtal_ff import PyXtal_FF
import os

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-d", "--data", dest="data", type=str,
                      help="path of data source, string", metavar='dataset')

    parser.add_option("-l", "--hiddenlayer", dest="hiddenlayer", type=str, default='6, 6',
                      help="hidden layer, ints separated by comma, e.g. 6, 6")

    parser.add_option("-a", "--activation", dest="activation", type=str,
                      help="activation function, e.g., tanh, tanh")

    parser.add_option("-f", "--force", dest="force", default=None, 
                      action='store_true',
                      help="calculate dxdr or not, default: False")

    parser.add_option("-s", "--stress", dest="stress", default=None,
                      action='store_true',
                      help="calculate rdxdr or not, default: False")

    parser.add_option("-e", "--elements", dest="elements", type=str,
                      help="elements separated by comma, e.g., Si, O")

    parser.add_option("-i", "--iteration", dest="iteration", type=int, default=100,
                      help="number of iterations for NN training, default: 100")

    parser.add_option("-t", "--type", dest="type", type=str, default='Bispectrum',
                      help="descriptor type: default: Bispectrum")

    parser.add_option("-c", "--cutoff", dest="cutoff", type=float, default=6.0,
                      help="cut off for descriptor calc: default: 6.0")


    (options, args) = parser.parse_args()

    train_data = options.data
    system = options.elements.split(',')
    if options.force is None:
        force = False
    else:
        force = True

    if options.stress is None:
        stress = False
    else:
        stress = True

    descriptor = {'type': options.type,
                  'Rc': options.cutoff,
                  'force': force,
                  'stress': stress,
                  'parameters': {'lmax': 3},
                 }


    hidden_layers = []
    for item in options.hiddenlayer.split(','):
        hidden_layers.append(int(item))

    activation = []
    if options.activation is None:
        for h in hidden_layers:
            activation.append('Tanh')
    else:
        activation = options.activation.split(',')

    activation.append('Linear')

    NN_model = {'system': system,
                'hiddenlayers': hidden_layers,
                #'activation': activation,
                'epoch': options.iteration,
                'force_coefficient': options.force,
                'stress_coefficient': options.stress,
                'optimizer': {'method': 'lbfgs'},
               }
    ff = PyXtal_FF(descriptors=descriptor, model=NN_model)
    ff.run(TrainData=train_data)
