name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          #pip install nose #pytest # flake8
          pip install pytest # flake8
          pip install --quiet -r requirements.txt
      - name: Test with pytest
        run: |
          python -m pytest pyxtal_ff/test_all.py

  notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pytest nbmake
          pip install -r requirements.txt
          pip install .
      - name: Test notebooks with pytest
        run: |
          pytest --nbmake ./examples
